# Generated by Django 3.2.6 on 2021-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
