# Generated by Django 3.2.6 on 2021-08-18 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210818_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 8, 18)),
        ),
    ]
