# Generated by Django 3.2.6 on 2021-08-18 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='date_created',
        ),
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
